### ISSUE TITLE
Bug: NameErrors dependent on function ordering

### ISSUE THREAD

**Issue by ajberdy** [amazon-braket/amazon-braket-sdk-python#832]
In Python, I can do this:

```
def func1():
    func2()

def func2():
    pass
```

but now we get a NameError if we have

```
@aq.main
def func1():
    func2()

@aq.subroutine
def func2():
    pass
```

This should be valid code

**Comment by ajberdy** [comment]
I wonder if we can fix this by keeping a registry of defined subroutines that the Program can references when run. In python we see the following behavior:
```
def f1():
    f2()


def f2():
    print("f2")


f1()
# prints "f2"


def f2():
    print("F2")

f1()
prints "F2"

```
Before the subroutine is defined, we can label it as an extern function in the Program object so the openqasm is valid

**Comment by rmshaffer** [comment]
I wonder if we could make the decorators use a lazy initialization pattern. So nothing really happens when the function is defined - it just returns a `Program` object in which the conversion has not happened yet. Then the first time the `Program` object is _used_ (i.e. any method or property is accessed), then the conversion happens.

**Comment by rmshaffer** [comment]
Closing this now that #841 has been merged into feature/autoqasm.
